lib/data/compression_options_data.c
lib/data/directory_data.c
lib/data/fragment_data.c
lib/data/inode_data.c
lib/data/metablock_data.c
lib/data/superblock_data.c
lib/data/xattr_data.c

This fixes compilation on FreeBSD:
```
#if defined(__FreeBSD__)
#include <sys/endian.h>
#else
#include <endian.h>
#endif
```

Fix compilation on FreeBSD

---

include/sqsh_directory_private.h
lib/directory/directory_iterator.c
test/directory/directory_iterator.c

during one of the last refactorings of the heap constructors, there was a bug introduced that caused a free of the wrong pointer. This commit fixes that bug, makes the wrongly freed pointer `const` to yield compiler warnings on misuse, and adds a test to make sure it doesn't happen again.

directory_iterator: fix wrong free, add tests

---

lib/reader/reader.c
test/metablock/metablock_reader.c

When growing a reader that is in buffered mode, the offset was not updated correctly. This caused the reader to append overlapping data twice and therefore corrupting the data.
This commit contains the fix as well as a test case for the metablock reader. Generalizing the test for the generic reader is left for later.

reader: fix handling of when growing a reader

---

lib/reader/reader.c

This changes reader_fill_buffer() to calculate the remaining size to be copied to the buffer instead of using the size that is already copied to the buffer. Also this commit adds assertions to check if the result of reader_fill_buffer() is sound.

reader: refactor reader_fill_buffer()

---

README.md
examples/readme_example.c

This commit adds an explanation to the example in the README.md file what it does. Also it links to further examples now.

README.md: add explanation to examples.

---

lib/easy/file.c

This fixes a bug in the file exists function where it would return false positives for files that do not exist.

easy/file: fix file exists function

---

.gitignore
subprojects/cextras.wrap

This updates the meson wrapfile for cextras to point to the right directory. This is needed because the meson wrapfile was not updated when the cextras subproject was included in the tree.

subproject: update meson wrapfile

---

include/sqsh_file.h
include/sqsh_mapper_private.h
include/sqsh_metablock_private.h
include/sqsh_reader_private.h
lib/file/file_iterator.c
lib/file/file_reader.c
lib/mapper/map_iterator.c
lib/mapper/map_reader.c
lib/metablock/metablock_iterator.c
lib/metablock/metablock_reader.c
lib/reader/reader.c
test/reader/reader.c

Implement _skip for data iterators.

---

lib/file/file_iterator.c
test/file/file_iterator.c

This fixes a bug where large zero blocks inside a file would result in the file iterator returning a block size that was too large. This may result in illegal memory access.

file_iterator: fix sparse handling

---

lib/directory/directory_iterator.c
test/directory/directory_iterator.c

when opening an SqshFile from a SqshDirectoryIterator, check that the information safed in the directory iterator are consistent with the information in the inode of the file.
This commit contains the fix and also a test case that reproduces the bug.

directory_iterator: consistency check on open

---

Makefile

meson generated didn't generate the `doc` target because it appended the output directory to the target name. This commit sets the output name to `.`, so that the target is named `doc` instead of `doc/html`.
fixes #75.

Makefile: fix doc target

---

lib/utils/error.c

Unfortunately, I didn't rename `SQSH_ERROR_UNKOWN_FILE_TYPE`, as that would be a breaking change.

Fix spelling of "unknown"

---

.github/codecov.yaml

This change adds a threshold to the codecov configuration. This is needed to let the CI not fail when small changes are made.

.github: add codecov.yaml configuration

---

lib/meson.build
meson.build

Up to now older versions of curl would fail to build as `curl_easy_header` was not defined. This change adds a version constraint to the dependency to make sure curl is only used if the version is new enough.

meson.build: add version constraint to libcurl

---

test/archive/compression_options.c
test/common.h
test/util.c

This change adds tests for all compression options to return the correct values. It also tests to get invalid compression options, which should return their UINT*_MAX values.

test: add in depth tests for compression options

---

include/sqsh_error.h
lib/utils/error.c

POSIX [does not require](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strerror.html#:~:text=The%20strerror()%20function%20need%20not%20be%20thread%2Dsafe.) `strerror` to be thread safe. Instead, use `strerror_r` to write into our own thread-local buffer.

Make sqsh_error_str thread safe, and document that the value may be overwritten

---

lib/easy/xattr.c
test/easy/xattr.c
test/meson.build

This change fixes a bug in `sqsh_easy_xattr_keys()` where the length of the key was set to the size of the value. This caused the return value of `sqsh_easy_xattr_keys()` to contain garbage.
This change also includes a test for sqsh_easy_xattr_keys() and `sqsh_easy_xattr_get()`.

easy: fix wrong key length in xattr.

---

include/sqsh_archive.h

The documentation for sqsh_inode_map_get() stated, that the function returns a negative error code on failure. The implementation however returns 0 on error. Inodes are always > 0, so using 0 as error code is safe.
fixes #106

include: fix documentation for sqsh_inode_map_get()

---

lib/extract/extract_manager.c
lib/extract/extractor.c

This change fixes two bugs where functions mask errors by either returning 0 or not checking the return value of another function.

extract: make sure return codes are propagated

---

lib/file/file_iterator.c
test/file/file_iterator.c

This change fixes the error code that was returned when a file iterator was initialized with a directory. Before this change, the iterator treated all file types as regular files and failed when they returned bogus file addresses. That works, but it is fragile and not the correct behavior.
This change adds a check to the iterator to ensure that it is initialized with a file and returns `-SQSH_ERROR_NOT_A_FILE` when it is not.
fixes #108.

file_iterator: return correct error when iterator is not a file

---

include/sqsh_metablock_private.h

sqsh__metablock_iterator_skip() was accidentally exported. It is a private function and therefor should not be exported.

metablock_iterator: _skip function is no longer exported

---

include/sqsh_directory.h
lib/directory/directory_iterator.c
lib/tree/walker.c
tools/fs3.c

This change deprecates sqsh_directory_iterator_inode_number() with a misleading return type (uint64_t) and replaces it with a new function sqsh_directory_iterator_inode() with a more appropriate return type (uint32_t). inodes in squashfs are by definition 32-bit, so there is no need to return a 64-bit. Also the function name is more consistent with the other functions in libsqsh.

directory_iterator: replace _inode_number with _inode

---

include/sqsh_directory.h
lib/directory/directory_iterator.c

This change partially reverts d068ca4 as it breaks the ABI compatibility of the library. It re-introduces sqsh_directory_iterator_inode_number() as a non-inline function.

directory_iterator: un-inline _inode_number

---

lib/tree/walker.c
test/tree/walker.c

Up to now the return code of the _next function was always 0, even if a next entry was found. The user of the walker had no way to check if the end of the tree was reached. This patch changes the return code to 1 if there is a next entry and 0 if the end of the directory is reached as defined in the documentation. It also adds a test for this case.

tree_walker: fix _next function.

---

include/sqsh_tree.h
lib/tree/walker.c
test/meson.build
test/tree/walker.c

This change introduces a new function sqsh_tree_walker_next2() which uses the same signature as sqsh_directory_iterator_next(). This harmonizes the API. For the next major release, the old function will be removed and _next2 will be renamed to _next.

tree_walker: introduce iterator-like _next2 function

---

include/sqsh_archive.h
include/sqsh_archive_private.h
lib/archive/archive.c
lib/archive/inode_map.c
lib/file/file.c
lib/tree/walker.c
test/archive/inode_map.c
tools/fs3.c

This changes the signature of _map_set() to take a uint32_t instead of an uint64_t. This harmonizes the inode type used in libsqsh to be uint32_t everywhere. For backwards compatibility, _map_set() is kept as a deprecated wrapper around _map_set2().

inode_map: Replace _map_set() with _map_set2()

---

include/sqsh_directory_private.h
lib/read/directory/directory_iterator.c
test/directory/directory_iterator.c

This change improves the inode calculation in the directory iterators. Before this change the inode was checked in check_inode_consistency() and then calculated naively in directory_iterator_inode(). After this change the inode is precalculated, checked more intensively and cached in update_inode(). director_iterator_inode() is a simple getter for the cached value.
This change also includes test cases for the directory iterator that check the new behavior.

directory_iterator: fix potential over-/underflow

---

lib/data/inode_data.c
lib/data/metablock_data.c

This changes the data access functions to use the leXXtoh functions instead of the accidentally used htoleXX functions. This shouldn't have an impact on the correctness as byte order swapping is involutional but it makes the code logically more correct.

data: replace htoleXX calls by leXXtoh

---

include/sqsh_file.h

This change rewrites documentation for the sqsh_file_iterator_skip(). It explains the behavior of the function itself better and focuses on the `offset` parameter as this seems to be a confusing part.

directory_iterator: improve documentation

---

lib/read/mapper/curl_mapper.c

This change sets a default minimum TLS version of 1.2 for all curl requests. This is stricter than curls default of TLSv1.0.

curl_mapper: enforce at least TLS v1.2

---

include/sqsh_tree.h
include/sqsh_tree_private.h
lib/read/easy/file.c
lib/read/file/file.c
lib/read/meson.build
lib/read/tree/path_resolver.c
lib/read/tree/walker.c
test/integration.c
test/meson.build
test/tree/path_resolver.c
tools/unpack.c

This change renames the tree walker to path resolver. This is done to better reflect the purpose of the struct and avoid misuse.

tree: rename walker to path resolver.

---

lib/read/metablock/metablock_iterator.c
test/meson.build
test/tools/ls/large-tree.sh

`extract_view` was not cleaned up properly when the iterator used the _skip() method. This caused a memory leak.
This change cleans up `extract_view` right before it is (re-)initialized. Also it adds a integration test that checks for this issue.

metablock_iterator: fix memory leak

---

tools/man/sqsh-cat.1.in
tools/man/sqsh-ls.1.in
tools/man/sqsh-stat.1.in
tools/man/sqsh-unpack.1.in
tools/man/sqsh-xattr.1.in
tools/src/cat.c
tools/src/common.h
tools/src/ls.c
tools/src/stat.c
tools/src/unpack.c
tools/src/xattr.c

This change introduces initial longopts support for the command line tools. It also updates the man pages to reflect the new options.

tools: support longopts

---

test/libsqsh/meson.build

This change calls the f2h.sh script with an absolute path. This fixes the build with muon with uses the build directory as the current working directory for calling scripts.

test: fix build with muon.

---

libsqsh/include/sqsh_extract_private.h
libsqsh/src/extract/extract_manager.c
libsqsh/src/extract/extractor.c

Instead of looking up the extractor implementation every time a new extractor is initialized, lookup the implementation once in the extract manager.

extract: lookup extractor implementation once

---

include/sqsh_easy.h
libsqsh/src/easy/directory.c
test/libsqsh/easy/directory.c

This change adds `sqsh_easy_directory_list_path()`, a function to list the contents of a directory as a list of file paths. This enables the user to get a list of paths that can be directly passed to other easy functions like `sqsh_easy_file_content()`.
This change also adds a test for the new function.

easy: add a function to list directory paths

---

test/tools/ls/utc.sh
test/tools/meson.build
tools/man/sqsh-ls.1.in
tools/src/ls.c

This change adds a `--utc` flag to `sqsh-ls`. This allows to ignore the local timezone and returns the mtime in UTC instead of local time.
This change was added to avoid the performance impact of calling localtime() for huge amounts of files.

sqsh-ls: add --utc flag

---

tools/src/ls.c

When calling `localtime(3)` by default it does a stat to `/etc/localtime`. It does that repeatedly for any call. As sqsh-ls has a short lifetime it would be enough (and also reduce the syscall overhead) to check it once.
Fortunally there's a workaround: These calls can be prevented by setting the TZ environment variable.[1]
This change sets the TZ variable if unset for `sqsh-ls` which greatly improves perfomance when listing many files.
[1] https://doc.dovecot.org/configuration_manual/system_calls_optimization/

ls: avoid `newfstatat` syscalls incritical path

---

libsqsh/include/sqsh_archive_private.h
libsqsh/src/archive/archive.c
libsqsh/src/file/file_iterator.c

This change reintroduces a dynamically allocated zero block. For now it has a fixed size. In contrast to a fixed rodata segment, dynamic allocations do not increase the build artifact size.

file_iterator: dynamically allocate zero block

---

libsqsh/src/file/file_iterator.c
test/libsqsh/file/file_iterator.c

Up to now sparse blocks at the end of a file were only calculated correctly for files that where exactly the size of a block.
This change fixes the behavior and introduces a test case to check for this behavior.

file_iterator: Correctly set the sparse_size.

---

libsqsh/include/sqsh_extract_private.h
libsqsh/src/extract/extractor.c
test/libsqsh/archive/compression_options.c

When building with optimisations enabled `sqsh__impl_lzo` was inlined in `extractor.c` this caused the tests to be unable to override this value to fake an extractor implementation.
This bug also broke the libsqsh-lzo[1] library when building libsqsh with optimizations enabled.
This change marks `sqsh__impl_lzo` as `volatile` which prevents inlining.
[1] https://github.com/Gottox/libsqsh-lzo

extract: fix tests when building with `-O2`

---

common/include/sqsh_data_set.h
common/src/data/superblock_set.c
common/src/meson.build
libmksqsh/include/meson.build
libmksqsh/include/sqsh_archive_builder.h
libmksqsh/meson.build
libmksqsh/src/archive/superblock_builder.c
libmksqsh/src/meson.build
meson.build
test/libsqsh/meson.build
test/libsqsh/util.c

This change introduces the first part of write support for libsqsh. The superblock_builder is a helper to create a superblock. It is currently used by the tests to generate the superblock for the test archive.

introduce superblock_builder

---

libsqsh/include/sqsh_file_private.h
libsqsh/src/file/file.c
libsqsh/src/file/inode_device.c
libsqsh/src/file/inode_directory.c
libsqsh/src/file/inode_file.c
libsqsh/src/file/inode_ipc.c
libsqsh/src/file/inode_null.c
libsqsh/src/file/inode_symlink.c

This change adds a new getter to retrieve the size of a symlink. Before this change the file_size getter was used to retrieve the size. This resulted in situations where the file size could be misinterpreted as a length for a symlink even though the file wasn't a symlink.

file: use own getter for the symlink size

---

tools/src/ls.c

This change makes ls escape the output filename paths, so that filenames with control characters do not mess up the output.

ls: escape output filename paths

---

tools/src/unpack.c

When unpacking a file fails, the file stream was not closed before returning. This patch fixes this issue by closing the file stream before returning.

unpack: fix dangling file stream

---

libsqsh/src/extract/zlib.c

The return value of the zlib inflate function is not neccessarily in the right format to be returned directly. While this is not a problem in itself (libsqsh regards any value smaller than 0 as an error), it is still a good practice to separate the return value from the out value.

extract: disconnect zlib return value from out value

---

libsqsh/include/sqsh_file_private.h
libsqsh/src/archive/inode_map.c
libsqsh/src/directory/directory_iterator.c
libsqsh/src/file/file.c
libsqsh/src/tree/path_resolver.c
libsqsh/src/tree/traversal.c
test/libsqsh/file/file.c
test/libsqsh/tree/traversal.c

This change removes the `dir_inode` field from the `SqshFile` structure and replaces it with a `parent_inode_ref` field. This field is used to store the inode reference of the parent directory. This reduces the number of inode lookups required to resolve the parent directory of a file.

file: use the inode reference for the parent directory.

---

include/sqsh_file.h
libsqsh/src/directory/directory_iterator.c
test/libsqsh/file/file.c
test/libsqsh/file/file_iterator.c
test/libsqsh/file/file_reader.c
test/libsqsh/xattr/xattr_iterator.c
tools/src/fs-common.c
tools/src/ls.c

This should never be returned. Rather than returning an unknown type, libsqsh does a consistency check and returns an error if the type is unknown.

file: remove unkown file type

---

libsqsh/src/tree/traversal.c
test/libsqsh/integration.c

It seems reasonable to extend the max_depth to do the reasonable thing when max_depth is 0 (yield only the root of the traversal, once)

Allow max_depth=0 for SqshTreeTraversal

---

libsqsh/src/tree/traversal.c
test/libsqsh/tree/traversal.c

Compute the size, and allocate only once with the exact size.  Build the path in reverse while walking the traversal stack, which avoids the need to call `sqsh_tree_traversal_path_segment` repeatedly (which must walk the traversal stack on each call).
In a simple benchmark (repeatedly calling `sqsh_easy_tree_traversal` against a simple squashfs file), this makes the entire `sqsh_easy_tree_traversal` call about 16% faster.

Optimize `sqsh_tree_traversal_path_dup`

---

libsqsh/include/sqsh_tree_private.h
libsqsh/src/tree/traversal.c

This allows re-using the stack items after popping.

Recycle stack items in SqshTreeTraversal on pop

---

subprojects/cextras.wrap
tools/meson.build
tools/src/unpack.c

This replaces the use of semaphores with the cextras library. This allows support for platforms that do not provide sem_t semaphores such as OpenBSD or have deprecated them such as macOS.

unpack: use cextras for semaphore

---

include/sqsh_posix.h

This commit adds sqsh_file_iterator_mt() to the include file. Also it adds the missing doxygen documentation for sqsh_threadpool_new().

posix: add missing file headers.

---

common/include/sqsh_reader_private.h
common/src/reader/reader.c
libsqsh/include/sqsh_extract_private.h
libsqsh/include/sqsh_file_private.h
libsqsh/include/sqsh_mapper_private.h
libsqsh/src/extract/extract_manager.c
libsqsh/src/extract/extract_view.c
libsqsh/src/file/file_iterator.c
libsqsh/src/file/fragment_view.c
libsqsh/src/mapper/map_iterator.c
libsqsh/src/mapper/map_manager.c
libsqsh/src/mapper/map_reader.c
subprojects/cextras.wrap
test/libsqsh/extract/extract_manager.c
test/libsqsh/integration.c

This function creates a copy of the iterator that has the same state as the original iterator.

file_iterator: implement a _copy() function

---

common/include/sqsh_data_private.h
common/src/data/inode_data.c
include/sqsh_file.h
libsqsh/include/sqsh_file_private.h
libsqsh/src/extract/lzma.c
libsqsh/src/file/file.c
libsqsh/src/file/file_iterator.c
libsqsh/src/file/inode_file.c
libsqsh/src/file/inode_null.c
tools/src/fs2.c
tools/src/fs3.c
tools/src/stat.c

This patch changes the block size and block compression functions to use 64bit indexing. From reading the specs, I came to the conclusion that the block size table can be larger than 4Gi entries. (to be exact, I believe that the worst case block table is:
UINT64_MAX (max file size) / 4096 (minimal block size)
While we don't support files that large yet, we lay the foundation to support them in the future.

file: use 64bit indexing for block size

---

subprojects/cextras.wrap

This update fixes a malbehaviour on 32bit systems, where the cextras library would calculate the wrong size for array resizing.
The corresponding commit in cextras is 2777280db867664211f072fc4bd6173a781ec8d4.
return -CX_ERR_INTEGER_OVERFLOW;
}
// Set the bit at the position of the first 0 to 1
-		*val = 1ULL << (sizeof(size_t) * 8 - leading_zeros);
+		*val = 1ULL << (sizeof(long long) * 8 - leading_zeros); } return 0; }
https://github.com/Gottox/cextras/commit/2777280db867664211f072fc4bd6173a781ec8d4

cextras: update to new main

---

tools/src/unpack.c

sqsh-unpack uses temporary files to store the extracted data. The temporary files were always created in the current working directory. This could lead to "Invalid cross-device link" errors when the current working directory is on a different file system than the target directory.

unpack: fix `Invalid cross-device link errors`

---

libsqsh/src/posix/file_ext.c
test/tools/meson.build
test/tools/unpack/empty_file.sh

file_ext: make sure file is always initialized when running a multithreaded iterator.

---

tools/include/sqshtools_common.h
tools/src/common.c
tools/src/unpack.c

When reading malformed archives, unpack may write error messages to stdout from multiple threads. This can result in interleaved output and garbled messages. To prevent this, a static mutex is added to output functions in common.c.

unpack: make sure stdout is locked
